### ISSUE TITLE
Compile all language support in one python file.

### ISSUE THREAD

**Issue by aashutoshrathi** [NJACKWinterOfCode/HackerRank-Test-Case-Generator#3]
The current structure of project provides different files for a different format of the logic file, merge them into one single file with if blocks.

**Comment by agarwalrounak** [comment]
I would like to work on the issue. Please assign it to me.

**Comment by aashutoshrathi** [comment]
Go for it @agarwalrounak

**Comment by agarwalrounak** [comment]
I have to create 3 python files- one for the Examples in Python3, the other for the Examples in Python2 and the third for the TC-Generators in Python2. Am I right?

**Comment by aashutoshrathi** [comment]
No, basically you have to create a single file which handle all folders - C, C++, Java etc
